# Generated by Django 5.1.4 on 2025-01-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField(default=3)),
                ('feedback_type', models.CharField(default='general', max_length=50)),
                ('agree', models.BooleanField(default=False)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
    ]
